Task10
Aceki/RTF-CPP-2020 pull request #10
Opened 2020-12-08 12:17 UTC by Aceki

2020-12-08 17:56 UTC, Toxin65 commented
Предлагаю сейчас не смотреть, а дождаться изменений в предыдущих частях.
Думаю они повлияют на эту...

2020-12-14 09:27 UTC, Toxin65 requested changes
Надо бы исправить 8, 9 до состояния отсутствия вопросов и зарешать конфликты (ребейзить). Тогда смотреть.

2020-12-22 13:13 UTC, Aceki commented
> Надо бы исправить 8, 9 до состояния отсутствия вопросов и зарешать конфликты (ребейзить). Тогда смотреть.

Готово

2020-12-22 18:10 UTC, Toxin65 requested changes
Не понял рандомизации.
И не уловил связи между построением дерева и лабиринта.
Возможно, всё правильно. Но не хватает грамотных комментов.

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +#include <iostream>
Много лишних инклудов осталось. Или мне кажется???

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +void printMTreeWeights(const int* weights, int mazeRows, int mazeColumns);
Нужно больше const-ов богу Const-ов! :)

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	direction startDir = static_cast<direction>(rand() % 4);
Рандомизировать бы rand...

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +					continue;
А это забавно. Но красиво, имхо.

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	buildFullMaze(maze, *startNode);
Ох как комментов нехватает.
Прокомментируйте, кто что делает.

2020-12-22 18:10 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +			iMaze.makeConnection(currentNode->i(), currentNode->j(), child->i(), child->j());
Не понял, где элемент рандомизации соединений...

2020-12-22 20:30 UTC, Aceki commented
> Не понял рандомизации.
> И не уловил связи между построением дерева и лабиринта.
> Возможно, всё правильно. Но не хватает грамотных комментов.

Что будет более правильным?
1. Создать дерево и на его основе построить лабиринт?
2. Создать лабиринт и на его основе построить дерево?

Сейчас у меня реализован первый вариант.

2020-12-23 17:20 UTC, Aceki commented
Для построения лабиринта используется немного изменённая версия этого алгоритма:
![image](https://user-images.githubusercontent.com/22858278/103022046-00141500-456d-11eb-81b2-c215099bfb21.png)

Френсис Хилл «OPENGL. ПРОГРАММИРОВАНИЕ КОМПЬЮТЕРНОЙ ГРАФИКИ»
с. 115

2020-12-23 18:04 UTC, Aceki commented on Task8-9-10/main.cpp
> +	direction startDir = static_cast<direction>(rand() % 4);
Чуть выше «srand(time(NULL))»

2020-12-25 08:05 UTC, Aceki commented on Task8-9-10/main.cpp
> +		//��������� ������ �������, ������� ����� �������������� ���������, �.�. ������ �currentNode�.
Случайный индекс потомка, который будет обрабатываться следующим, т.е. станет «currentNode».

2020-12-25 08:06 UTC, Aceki commented on Task8-9-10/main.cpp
> +		//�������� ��������� ������� ����������� � ���� ���������
Случайно выбранный потомок добавляется в стек последним
Это позволит начать обработку с него в следующей итерации

2020-12-25 08:07 UTC, Aceki commented on Task8-9-10/main.cpp
> +	srand(time(NULL));
Инициализация генератора случайных чисел.

2020-12-26 17:12 UTC, merged