Task210215
Aceki/RTF-CPP-2020 pull request #15
Opened 2021-02-19 06:54 UTC by Aceki

2021-02-22 12:21 UTC, Toxin65 requested changes
В целом нелохо. Есть интересные подходы.
Но есть и серьёзные ошибки. Будем разбирать на практике, видимо.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/amperage.h
> +	double value();
Геттер, конечно же, должен быть const.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/complex.cpp
> +				   m_imaginary * number.m_real + m_real * number.m_imaginary);
Формулу проверьте. Похоже там ошибочка закралась.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/position.h
> +	};
Нуууу... Это же неудобно.
А как перемещаться между ними? Допустим, я хочу сместиться влево на N клеток. Или хочу найти между клетками расстояние.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector4d.h
> +		const double m_t;
Это, само собой, сильный подход, когда для модификации вектора нужно порождать новый объект.
И это не первое место, где вы такое делаете. Но развет оно того стоит?
А как же operator*=, к примеру...?
Я не против, этот подход имеет место. Но оправдан ли он в данном случае?

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector4d.h
> +	Vector4D operator*(const Vector4D& vec, const double& number);
А почему double по ссылке?

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector4d.h
> +		Vector4D operator/(const double& number) const;
Кстати, в некоторых случаях может быть уместно для таких структур определять operator[]

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector2d.h
> +#include "vector3d.h"
Кажется, достаточно было здесь его объявить, а не тащить весь заголовочник.
И да, вы интересно интерпретировали задание. Я то позже уже посмотрел, что надо было либо потребовать псевдоскалярное произведение, либо вектора потребовать трёхмерные.
Но я принимаю ваш подход -- он, по сути, верный, в условиях неопределённости задания.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector2d.h
> +		Vector2D() : Vector2D(0, 0) { }
А зачем так делать? Лучше всего инициализировать поля при объявлении.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector2d.cpp
> +	return Vector3D::k() * (vec1.m_x * vec2.m_y - vec2.m_x * vec1.m_y);
Неплохо!

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/vector3d.cpp
> +	return Vector3D::i() * (vec1.m_y * vec1.m_z - vec2.m_y * vec2.m_z) +
Ошибка в формуле. Проверьте.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +    * 3.1) vector<T> because the sequence of moves is a changing set.
Верно.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +    * 3.2) Didn't understand the wording.
Разберём на паре.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +    * 4.2) vector<T>
К сожалению, задание не очень чётко описано...
Оба неверно.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/physical_quantity.h
> +		PhysicalQuantity operator+(const PhysicalQuantity& quantity);
А чего они все не const?

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/physical_quantity.h
> +		const char* m_sign;
Лучше, наверно, std::string. Хотя и так нормально.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/physical_quantity.cpp
> +	return PhysicalQuantity(value() + quantity.value(), "?");
Не, тут всё надо через dynamic_cast, а у вас получается что перемножать можно что угодно на что угодно.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/power.h
> +		explicit Power(double value) : PhysicalQuantity(value, "N") { }
Разве так можно? Я про "N"

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/power.h
> +		Power operator/(const Power& power) const;
Пааажи... А что, разве мощность умножить на мощность получится мощность. То же самое и с делением.
Задача была выполнить все физически верные (да, этого явно не указано в задании) операции.
Т.е. Па = Н/м2 и все от неё производные. Одинаковые величины можно междй собой складывать и вычитать, а ещё можно умножать на скаляр, это допустимо.
Ну и это касается всех величин.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +    * 5.6) physical_quantity.h physical_quantity.cpp
К сожалению, фундаментальные ошибки в решении всего п.5

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +}
А мы алгоритмы не разбирали?
Просто писать пузырёк -- это лишнее...

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +T* bubbleSort(T* arr, int (*cmp)(const T& first, const T& second), int size)
А чего функция возвращает int?
Так, обычно, не принято делать.

2021-02-22 12:21 UTC, Toxin65 commented on Task210215/main.cpp
> +  6) main.cpp
6-ое задание -- overkill. Не обязательно было писать шаблон.
Ну да ладно. В целом идея верная. За исключением функции сравнения, которая возвращает int.

2021-02-22 13:36 UTC, Aceki commented on Task210215/amperage.h
> +	double value();
Тогда не получится подсчитывать кол-во считываний.

2021-02-22 13:54 UTC, Toxin65 commented on Task210215/amperage.h
> +	double value();
Конечно же получится. Вы просто кое-что забыли, видимо.

2021-02-23 09:15 UTC, Aceki commented on Task210215/power.h
> +		explicit Power(double value) : PhysicalQuantity(value, "N") { }
Ньютоны

2021-02-23 09:25 UTC, Aceki commented on Task210215/main.cpp
> +T* bubbleSort(T* arr, int (*cmp)(const T& first, const T& second), int size)
Это функция сравнения. 
Возвращает:
 — Положительное число, если первый аргумент больше второго.
 — Отрицательное, если наоборот.
 — Нуль, если они равны.
 Тот же механизм используется, например, в методе CompareTo интерфейса IComparable языка C#.

2021-02-23 09:26 UTC, Aceki commented on Task210215/main.cpp
> +T* bubbleSort(T* arr, int (*cmp)(const T& first, const T& second), int size)
![image](https://user-images.githubusercontent.com/22858278/108824092-20029c00-75e3-11eb-85a6-dd6eb099c589.png)

2021-02-23 09:51 UTC, Toxin65 commented on Task210215/main.cpp
> +T* bubbleSort(T* arr, int (*cmp)(const T& first, const T& second), int size)
В стандартной библиотеке шаблонов STL, да и повсеместно в плюсах, используется функция сравнения, возвращающая bool/

2021-02-23 09:53 UTC, Toxin65 commented on Task210215/power.h
> +		explicit Power(double value) : PhysicalQuantity(value, "N") { }
Сам себе отвечу. Можно. Нело не в Ньютонах, а в том, что строковая константа расположена, как будто, на стеке. На самом деле нет.

2021-02-23 12:36 UTC, Aceki commented on Task210215/main.cpp
> +T* bubbleSort(T* arr, int (*cmp)(const T& first, const T& second), int size)
Спасибо! Буду знать

2021-03-10 13:10 UTC, closed without merging