Task8
Aceki/RTF-CPP-2020 pull request #3
Opened 2020-11-20 04:26 UTC by Aceki

2020-11-20 04:26 UTC, Aceki commented on Task8/MCell.h
> +	//true => ������ ������.
true => проход открыт

2020-11-20 04:52 UTC, Aceki commented on Task8/path.h
> +	//urdl
up right down left

2020-11-21 06:47 UTC, solodyankina reviewed
не компилирует

2020-11-21 10:28 UTC, Toxin65 requested changes
Не соответствует ТЗ.

2020-11-21 10:28 UTC, Toxin65 commented on Task8/MCell.h
> +	MCell(bool down = false, bool right = false) : m_down(down), m_right(right) {}
Не соответствует ТЗ.

2020-11-21 10:33 UTC, Toxin65 commented
Не до конца проверил. Проверю попозже. Если что -- напомните о себе.

2020-11-22 11:30 UTC, Toxin65 requested changes
Задумки хорошие. Но кое-что нужно обязательно исправить.

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +	throw "Not a neighbours!";
English grammar! "Not a neighbour" or "Not neighbours"

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +		return side::right;
Вообще странно, обычно i, j -> строка, столбец

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +		return L'°';
Я подумал, может лучше '0'? (Да, да, в ТЗ написано другое)

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +	case path::left_down_right:
Логику потерял... Может сначала верх/низ, потом право/лево? И всегда этого придерживаться...
Ни на что не влияет. Это общее соображение.

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +}
В общем, он особо не нужен. Можно было просто его удалить.

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +	int m_field_length = obj.m_n * obj.m_m;
Можно было считать сразу в new, и через свои поля. Зачем снова запрашивать то, что уже есть у себя? (вкусовщина, в принципе, согласен)

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.cpp
> +			flag = flag << 1 | left;
Это не самый лучший подход. Лучше что-то вида ```flag = (flag_up*up) | (flag_down*down) ...```
Либо ```if(up) flag|=flag_up```
У вас играет роль порядок строк и значения битовых флагов, а это нехорошо. А сами флаги вообще не вигурируют в рамках выражений.

2020-11-22 11:30 UTC, Toxin65 commented on Task8/Maze.h
> +	wchar_t getPathChar(path path) const;
Он же static...

2020-11-22 11:30 UTC, Toxin65 commented on Task8/main.cpp
> +    maze.makeConnection(4, 3, 4, 4);
Мне это не нравится. У вас makeConnection и removeConnection false не возвращают вообще, зато падают с исключением. ТЗ задумано иначе. Кидать исключение не надо. Не можешь -- верни false.

2020-11-22 11:30 UTC, Toxin65 commented on Task8/path.h
> +enum class path
Давайте сделаем его внутренним для класса Maze.
А зачем прямо enum class, почему не просто enum?

2020-11-22 11:30 UTC, Toxin65 commented on Task8/side.h
> +enum class side
То же, давайте его внесём в класс Maze.

2020-11-23 16:36 UTC, Aceki commented on Task8/path.h
> +enum class path
Конфликт с enum side: одинаковые названия флагов.

2020-11-23 17:06 UTC, closed without merging

2020-11-24 11:26 UTC, Aceki commented on Task8/path.h
> +enum class path
Исправлено.

2020-11-24 11:32 UTC, Aceki commented on Task8/main.cpp
> +    maze.makeConnection(4, 3, 4, 4);
Исправления здесь: https://github.com/Aceki/RTF-CPP-2020/pull/4

2020-11-24 11:32 UTC, Aceki commented on Task8/Maze.h
> +	wchar_t getPathChar(path path) const;
Исправления здесь: https://github.com/Aceki/RTF-CPP-2020/pull/4

2020-11-24 11:32 UTC, Aceki commented on Task8/Maze.cpp
> +			flag = flag << 1 | left;
Исправления здесь: https://github.com/Aceki/RTF-CPP-2020/pull/4