Task9
Aceki/RTF-CPP-2020 pull request #9
Opened 2020-12-08 12:15 UTC by Aceki

2020-12-08 17:55 UTC, Toxin65 requested changes
Надо бы доработать...

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.h
> +	MTreeNode* m_children;
Все поля надо инициализировать при объявлении. Обязательно.
Хуже от этого точно не будет. А лучше -- может быть. Можно не думать о значениях по-умолчанию.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.h
> +	MTreeNode();
Сначала методы, потом поля.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.h
> +};
Желательно всегда оставлять пустую строку в конце файла.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	node->m_parent = nullptr;
Вот эти три поля не надо было бы писать, если инициализировать при объявлении полей.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	node->m_children = new MTreeNode[4];
Если количество потомков фиксировано, то какой смысл выделять всегда 4 элемента динамически?
[потому что ТЗ такое, ага]
Ладно. ТЗ не противоречит. Пусть будет так. Это разумно.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	if (m_children == nullptr)
Этого не надо. delete спокойно периваривает nullptr с некоторых пор.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	m_parent = m_children = nullptr;
Сделайте по-человечески. И этот конструктор тогда вообще не нужен.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	m_distance = parent->distance() + 1;
Указатель приходит. Надо бы ассерт на нуллптр, прежде чем к нему обращаться...

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	m_children = new MTreeNode[4];
Мда...

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	int offset_j = m_j - j;
const же!!!
Вообще лучше везде const, где можно его поставить.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	if (abs(offset_i) + abs(offset_j) != 1)
Вооо, проверочка подъехала грамотная!

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	child->m_children = new MTreeNode[4];
Выглядит ужасно. Но я сам виноват, ибо писал ТЗ...
С точки зрения ТЗ всё хорошо.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +#pragma endregion
Но это же наркомания! :facepalm: 
Надо просто написать метод, который будет строить готовое дерево по имеющемуся экземпляру Maze. А ещё лучше, обновлять дерево по экземпляру Maze.
Уж я думал, что здесь накосячить невозможно! А оказывается возможно, и ещё как!
ТЗ, допустим, не противоречит. Но дальше то траблы будут жёсткие...
Я пересмотрю ТЗ. Это ужасно!

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
А как вы гарантируете отсутствие циклов, кроме своей сознательности?
Вам тут лямбды очень бы пригодились. Хотя можно сделать и внешними функциями.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
Но при таком подходе, здесь всё сильно проще, само собой.
Но что будет дальше?
Я всё же настаиваю, что первичная информация -- это Maze, а дерево -- вторичная.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	{
Если вы ставите отдельный блок когда, вам всё равно надо писать `#pragma region`?

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
Вынести бы в отдельную функцию. Может не сейчас, но в принципе это разумно.

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +		vector<const MTreeNode*> nodes;
reserve

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +		weights[i] = new int[mazeColumns];
А чё так рано? Ещё целый блок впереди...

2020-12-08 17:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	int** weights = new int*[mazeRows];
Вы же знаете вектор, зачем наркоманию разводить, раз уже использовали...

2020-12-08 18:38 UTC, Aceki commented on Task8-9-10/main.cpp
> +	}
Изначально было множество полезных отдельных функций, но в таком виде у меня отказались принимать решение.
Пришлось делать так.

2020-12-08 18:53 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
А где были полезные функции? Или это были полезные методы?

2020-12-08 19:46 UTC, Aceki commented on Task8-9-10/main.cpp
> +	}
Была отдельная функция для подсчета весов, в ней использовалась рекурсия; функция для заполнения лабиринта на основе дерева MTreeNode, похожая на ту, что вы вводите в следующей части технического задания.

2020-12-08 19:51 UTC, Aceki commented on Task8-9-10/main.cpp
> +	}
Также была функция makeChain, которая позволяла создать цепь из узлов, теперь она размазана по региону «LadderTreeCreating».

2020-12-09 04:55 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
Если это именно функции в main.cpp, то это норм подход...
Согласно ТЗ классы необоснованно расширять нельзя. А в main то пожалуйста.

2020-12-09 10:30 UTC, Aceki commented on Task8-9-10/main.cpp
> +	}
![image](https://user-images.githubusercontent.com/22858278/101618193-7542fe80-3a33-11eb-8549-10eedf43d1ac.png)

2020-12-09 11:51 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
Можно. Но функция должна быть обоснованным решением...
Имеется в виду, что если она создана по глупости (неправильная архитектурна, не нужна, ибо маленькая дак ещё и вызывается в одном месте, причин может быть много...) -- то я могу задать вопрос.

2020-12-09 17:47 UTC, Aceki commented on Task8-9-10/MTreeNode.cpp
> +	m_children[m_child_count++] = std::move(child);
Что думаете о таком подходе?

2020-12-11 11:13 UTC, Aceki commented on Task8-9-10/main.cpp
> +	}
Получается, что дерево нужно строить согласно лабиринту?

2020-12-11 11:21 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +	}
Скорее даже верифицировать и обновлять согласно лабиринту...

2020-12-11 11:26 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	m_children[m_child_count++] = std::move(child);
Или я чего-то не понимаю. Или вы не знаете семантику переноса.
Но выглядит это ужасно.

2020-12-14 09:20 UTC, Toxin65 requested changes

2020-12-14 09:20 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	obj.m_parent = nullptr;
А это зачем?

2020-12-14 09:20 UTC, Toxin65 commented on Task8-9-10/MTreeNode.h
> +	MTreeNode& operator=(const MTreeNode & obj) = delete;
Норм.

2020-12-14 09:20 UTC, Toxin65 commented on Task8-9-10/main.cpp
> +			std::cout << weights[i * mazeColumns + j] << ' ';
![image](https://user-images.githubusercontent.com/31862/102063069-5ff51800-3e17-11eb-8bdf-d650670c5509.png)

Веса не выводятся... Что-то напортачено с выводом.

2020-12-14 12:53 UTC, Aceki commented on Task8-9-10/MTreeNode.cpp
> +	obj.m_parent = nullptr;
this берёт контроль над памятью объекта obj.

2020-12-14 12:57 UTC, Aceki commented on Task8-9-10/main.cpp
> +			std::cout << weights[i * mazeColumns + j] << ' ';
Здравствуйте! У меня всё в порядке.
![image](https://user-images.githubusercontent.com/22858278/102083704-d0ab2d00-3e35-11eb-8eb2-0d64dfb93698.png)

2020-12-14 12:58 UTC, Aceki commented on Task8-9-10/main.cpp
> +			std::cout << weights[i * mazeColumns + j] << ' ';
У вас точка останова стоит, может быть, в ней проблема.

2020-12-20 08:05 UTC, Aceki commented on Task8-9-10/main.cpp
> +			std::cout << weights[i * mazeColumns + j] << ' ';
Попробовал скомпилировать с помощью «g++».  Действительно, веса не выводятся. Удалось решить проблему заменив "std::cout" на "std::wcout".

2020-12-22 09:57 UTC, Toxin65 approved these changes
Небольшое замечание.
wcout помог.
Хорошая работа!

2020-12-22 09:57 UTC, Toxin65 commented on Task8-9-10/MTreeNode.cpp
> +	obj.m_parent = nullptr;
Думал верно, но нет.
Родитель то тут не при делах... Потомок памятью родителя не управляет.

2020-12-26 17:11 UTC, merged